# run this style config from the directory above config/data/logs with -Des.config=config/elasticsearch.yml (tested on Mac only!)

# Node name is provided by the script based on the directory name. But it can be overridden if desired
#node.name: "NodeName"

# Enable [path.conf] if you want to customize logging.yml file as well by copying it into the same - local - directory. 
# Otherwise, the install-directory one will be used. We don't need this for elasticsearch.yml only, as we are pointing to it directly with the command line param
#path.conf: "config"

path.data: "data"
path.logs: "logs"
path.work: "temp"

marvel.agent.enabled: false
